version: '3.7'

services:
  web:
    build:
       dockerfile: Dockerfile.prod
       context: .
    command: gunicorn adquity_django.wsgi:application --bind 0.0.0.0:8000 --timeout 3600
    expose:
      - 8000
    env_file:
      - ./.env.prod     
  nginx:
    build: ./nginx
    ports:
     - 80:80
    depends_on:
     - web