version: '3.7'

services:
  web:
    build:
       dockerfile: Dockerfile.prod
       context: .
    command: gunicorn adquity_django.wsgi:application --bind 0.0.0.0:8000 --timeout 3600
    expose:
      - 8000
    env_file:
      - ./.env.prod     
  nginx:
    build: ./nginx
    ports:
     - 80:80
     - 443:443
    depends_on:
     - web
    volumes:
     - ./data/certbot/conf:/etc/letsencrypt
     - ./data/certbot/www:/var/www/certbot
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
  certbot:
    image: certbot/certbot
    volumes:
     - ./data/certbot/conf:/etc/letsencrypt
     - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"