# Generated by Django 3.1 on 2020-09-06 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('semapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Upload',
        ),
    ]
