# Generated by Django 3.1 on 2020-09-25 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('semapp', '0002_delete_upload'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('view', 'view'), ('submit', 'submit'), ('process', 'process'), ('error', 'error')], default='view', max_length=10)),
                ('time', models.DateTimeField()),
                ('user_name', models.CharField(max_length=200)),
                ('origin', models.CharField(max_length=200)),
                ('info', models.JSONField()),
            ],
        ),
    ]
