# Generated by Django 3.1 on 2020-09-25 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semapp', '0003_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='info',
            field=models.JSONField(blank=True),
        ),
    ]
