# Generated by Django 3.1 on 2020-09-25 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semapp', '0004_auto_20200925_2354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='info',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
